import rawCatalog from "../data/eclipses.json";
import type { EclipseEvent, EclipseType } from "./types";

/** All eclipses 1950–2100, sorted by peak time. Generated by scripts/generate-catalog.mjs. */
export const CATALOG = rawCatalog as EclipseEvent[];

const byId = new Map(CATALOG.map((e) => [e.id, e]));

export function getEclipse(id: string): EclipseEvent | undefined {
  return byId.get(id);
}

/** Index of the first event with peakMs > t (binary search). */
function upperBound(t: number): number {
  let lo = 0;
  let hi = CATALOG.length;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (CATALOG[mid].peakMs <= t) lo = mid + 1;
    else hi = mid;
  }
  return lo;
}

export function nextEclipse(afterMs: number, type?: EclipseType): EclipseEvent | undefined {
  for (let i = upperBound(afterMs); i < CATALOG.length; i++) {
    if (!type || CATALOG[i].type === type) return CATALOG[i];
  }
  return undefined;
}

export function prevEclipse(beforeMs: number, type?: EclipseType): EclipseEvent | undefined {
  for (let i = upperBound(beforeMs - 1) - 1; i >= 0; i--) {
    if (!type || CATALOG[i].type === type) return CATALOG[i];
  }
  return undefined;
}

/** The eclipse whose peak is closest to t (either direction). */
export function nearestEclipse(t: number): EclipseEvent {
  const next = nextEclipse(t);
  const prev = prevEclipse(t);
  if (!next) return prev!;
  if (!prev) return next;
  return next.peakMs - t < t - prev.peakMs ? next : prev;
}

/**
 * The eclipse "happening" around time t — the selected one if t falls inside
 * its event window, else the nearest one if inside its window, else null.
 * Windows match the fine-slider spans (solar ±4 h, lunar ≥ ±6 h).
 */
/**
 * Half-width of the "eclipse is happening" window around a peak — drives the
 * fine slider's range, the auto-stop, and the camera lock's availability.
 * ±2 h keeps the slider tight around the spectacle: the longest lunar UMBRAL
 * phases span ±118 min (penumbral tails are invisible to the eye), and while
 * the most extreme solar partial phases stretch to ~±2.7 h, coverage out
 * there is a sliver — the heart of every event sits well inside.
 */
export function eclipseHalfWindowMs(_e: EclipseEvent): number {
  return 2 * 3600_000;
}

export function activeEclipse(t: number, selectedId?: string | null): EclipseEvent | null {
  const candidates = [selectedId ? byId.get(selectedId) : undefined, nearestEclipse(t)];
  for (const e of candidates) {
    if (!e) continue;
    if (Math.abs(t - e.peakMs) <= eclipseHalfWindowMs(e)) return e;
  }
  return null;
}
